In [14]:
import pypose as pp
import torch

# use float64 for better precision in torch
torch.set_default_dtype(torch.float64)
torch.set_printoptions(precision=10)


In [10]:
# Cam0
R_velo_to_cam = torch.tensor([7.967514e-03,-9.999679e-01,-8.462264e-04,-2.771053e-03,8.241710e-04,-9.999958e-01,9.999644e-01,7.969825e-03,-2.764397e-03]).reshape(3,3).cuda()
t_velo_to_cam = torch.tensor([-1.377769e-02,-5.542117e-02,-2.918589e-01]).cuda()
R_imu_to_velo = torch.tensor([9.999976e-01,7.553071e-04,-2.035826e-03,-7.854027e-04,9.998898e-01,-1.482298e-02,2.024406e-03,1.482454e-02,9.998881e-01]).reshape(3,3).cuda()
t_imu_to_velo = torch.tensor([-8.086759e-01,3.195559e-01,-7.997231e-01]).cuda()

/opt/conda/envs/nerfstudio/lib/python3.10/site-packages/pypose/lietensor/lietensor.py:917: UserWarning: Tensor Shape Invalid by calling <built-in method cat of type object at 0x7f983c162540>, go to https://pypose.org/docs/main/generated/pypose.LieTensor
  warnings.warn('Tensor Shape Invalid by calling {}, ' \


In [11]:
q_velo_to_cam = pp.mat2SO3(R_velo_to_cam)
T_velo_to_cam = pp.SE3(torch.cat([t_velo_to_cam, q_velo_to_cam], dim=-1))
q_imu_to_velo = pp.mat2SO3(R_imu_to_velo)
T_imu_to_velo = pp.SE3(torch.cat([t_imu_to_velo, q_imu_to_velo], dim=-1))
T_imu_to_cam = (T_velo_to_cam @ T_imu_to_velo)
T_cam_to_imu = T_imu_to_cam.Inv()

In [18]:
T_imu_to_cam.matrix().flatten()

tensor([ 0.0087511861, -0.9998642288,  0.0139601509, -0.3390897324,
        -0.0047961109, -0.0140024663, -0.9998904301,  0.7468028460,
         0.9999501783,  0.0086832454, -0.0049179702, -1.0957484538,
         0.0000000000,  0.0000000000,  0.0000000000,  1.0000000000],
       device='cuda:0')

In [29]:
T_cam_to_imu.matrix().flatten()

tensor([ 0.0087511861, -0.0047961109,  0.9999501783,  1.1022430484,
        -0.9998642288, -0.0140024663,  0.0086832454, -0.3190719593,
         0.0139601509, -0.9998904301, -0.0049179702,  0.7460659045,
         0.0000000000,  0.0000000000,  0.0000000000,  1.0000000000],
       device='cuda:0')

In [37]:
# Cam1
R_cam1_to_cam = torch.tensor([9.993424e-01,1.830363e-02,-3.129928e-02,-1.856768e-02,9.997943e-01,-8.166432e-03,3.114337e-02,8.742218e-03,9.994767e-01]).reshape(3,3).cuda()
t_cam1_to_cam = torch.tensor([-5.370000e-01,5.591661e-03,-1.200541e-02]).cuda()
T_cam1_to_cam = pp.SE3(torch.cat([t_cam1_to_cam, pp.mat2SO3(R_cam1_to_cam)], dim=-1))
T_imu_to_cam1 = T_cam1_to_cam @ (T_velo_to_cam @ T_imu_to_velo)
T_cam1_to_imu = T_imu_to_cam1.Inv()

In [38]:
T_cam1_to_imu.matrix().flatten()

tensor([-0.0226400778, -0.0131236383,  0.9996575117,  1.1021600067,
        -0.9997348439,  0.0044946607, -0.0225828505, -0.8562258198,
        -0.0041967248, -0.9999037521, -0.0132218903,  0.7492446519,
         0.0000000000,  0.0000000000,  0.0000000000,  1.0000000000],
       device='cuda:0')